-- ============================================================
-- MIGRATION: Purchase Order
-- Duratu Kafe ERP
--
-- Membuat:
-- 1. Sequence nomor Purchase Order.
-- 2. Tabel purchase_orders.
-- 3. Tabel purchase_order_items.
-- 4. Constraint dan index.
-- 5. RPC create_purchase_order_from_request.
--
-- Alur:
-- Purchase Request approved
--          ↓
-- Purchase Order draft
--          ↓
-- Purchase Request converted
--
-- Pembuatan PO belum menambah stok.
-- Stok hanya berubah ketika Goods Receipt diproses.
-- ============================================================


-- ============================================================
-- 1. PASTIKAN STATUS PURCHASE REQUEST MENDUKUNG "converted"
-- ============================================================

do $$
declare
  v_constraint record;
begin
  for v_constraint in
    select
      con.conname
    from pg_constraint as con
    join pg_class as cls
      on cls.oid = con.conrelid
    join pg_namespace as ns
      on ns.oid = cls.relnamespace
    join pg_attribute as attr
      on
        attr.attrelid = cls.oid
        and attr.attnum = any(con.conkey)
    where
      ns.nspname = 'public'
      and cls.relname = 'purchase_requests'
      and con.contype = 'c'
      and attr.attname = 'status'
  loop
    execute format(
      'alter table public.purchase_requests drop constraint if exists %I',
      v_constraint.conname
    );
  end loop;
end;
$$;

alter table public.purchase_requests
add constraint purchase_requests_status_valid
check (
  status in (
    'draft',
    'submitted',
    'approved',
    'rejected',
    'converted',
    'cancelled'
  )
);


-- ============================================================
-- 2. SEQUENCE NOMOR PURCHASE ORDER
-- ============================================================

create sequence if not exists
public.purchase_order_number_seq
as bigint
start with 1
increment by 1
minvalue 1
no maxvalue
cache 1;


-- ============================================================
-- 3. TABEL PURCHASE ORDERS
-- ============================================================

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,

  order_number text not null,

  purchase_request_id bigint,
  supplier_id bigint not null,

  status text not null default 'draft',

  order_date date not null default current_date,
  expected_date date,

  notes text,

  subtotal numeric(18, 2) not null default 0,
  discount_amount numeric(18, 2) not null default 0,
  tax_amount numeric(18, 2) not null default 0,
  total_amount numeric(18, 2) not null default 0,

  sent_at timestamptz,
  confirmed_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,

  cancellation_reason text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint purchase_orders_order_number_unique
    unique (order_number),

  constraint purchase_orders_purchase_request_unique
    unique (purchase_request_id),

  constraint purchase_orders_purchase_request_id_fkey
    foreign key (purchase_request_id)
    references public.purchase_requests(id)
    on update cascade
    on delete restrict,

  constraint purchase_orders_supplier_id_fkey
    foreign key (supplier_id)
    references public.suppliers(id)
    on update cascade
    on delete restrict,

  constraint purchase_orders_status_valid
    check (
      status in (
        'draft',
        'sent',
        'confirmed',
        'partial_received',
        'completed',
        'cancelled'
      )
    ),

  constraint purchase_orders_subtotal_non_negative
    check (subtotal >= 0),

  constraint purchase_orders_discount_amount_non_negative
    check (discount_amount >= 0),

  constraint purchase_orders_tax_amount_non_negative
    check (tax_amount >= 0),

  constraint purchase_orders_total_amount_non_negative
    check (total_amount >= 0),

  constraint purchase_orders_expected_date_valid
    check (
      expected_date is null
      or expected_date >= order_date
    ),

  constraint purchase_orders_cancellation_reason_valid
    check (
      cancellation_reason is null
      or char_length(btrim(cancellation_reason)) between 5 and 500
    )
);


-- ============================================================
-- 4. TABEL PURCHASE ORDER ITEMS
-- ============================================================

create table if not exists public.purchase_order_items (
  id bigint generated by default as identity primary key,

  purchase_order_id bigint not null,
  product_id bigint not null,

  quantity numeric(18, 3) not null,
  received_quantity numeric(18, 3) not null default 0,

  unit_cost numeric(18, 2) not null,
  subtotal numeric(18, 2) not null,

  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint purchase_order_items_purchase_order_id_fkey
    foreign key (purchase_order_id)
    references public.purchase_orders(id)
    on update cascade
    on delete cascade,

  constraint purchase_order_items_product_id_fkey
    foreign key (product_id)
    references public.products(id)
    on update cascade
    on delete restrict,

  constraint purchase_order_items_product_unique
    unique (
      purchase_order_id,
      product_id
    ),

  constraint purchase_order_items_quantity_positive
    check (quantity > 0),

  constraint purchase_order_items_received_quantity_non_negative
    check (received_quantity >= 0),

  constraint purchase_order_items_received_quantity_valid
    check (received_quantity <= quantity),

  constraint purchase_order_items_unit_cost_non_negative
    check (unit_cost >= 0),

  constraint purchase_order_items_subtotal_non_negative
    check (subtotal >= 0)
);


-- ============================================================
-- 5. INDEX
-- ============================================================

create index if not exists
purchase_orders_supplier_id_idx
on public.purchase_orders(supplier_id);

create index if not exists
purchase_orders_purchase_request_id_idx
on public.purchase_orders(purchase_request_id);

create index if not exists
purchase_orders_status_idx
on public.purchase_orders(status);

create index if not exists
purchase_orders_order_date_idx
on public.purchase_orders(order_date desc);

create index if not exists
purchase_orders_expected_date_idx
on public.purchase_orders(expected_date);

create index if not exists
purchase_order_items_purchase_order_id_idx
on public.purchase_order_items(purchase_order_id);

create index if not exists
purchase_order_items_product_id_idx
on public.purchase_order_items(product_id);


-- ============================================================
-- 6. FUNCTION PEMBUAT NOMOR PURCHASE ORDER
-- ============================================================

create or replace function public.generate_purchase_order_number()
returns text
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_sequence_value bigint;
begin
  v_sequence_value :=
    nextval(
      'public.purchase_order_number_seq'
    );

  return
    'PO-'
    || to_char(
      current_date,
      'YYYYMMDD'
    )
    || '-'
    || lpad(
      v_sequence_value::text,
      6,
      '0'
    );
end;
$$;


-- ============================================================
-- 7. RPC CREATE PURCHASE ORDER FROM PURCHASE REQUEST
-- ============================================================

create or replace function public.create_purchase_order_from_request(
  p_purchase_request_id bigint,
  p_order_date date default current_date,
  p_expected_date date default null,
  p_notes text default null,
  p_discount_amount numeric default 0,
  p_tax_amount numeric default 0
)
returns table (
  purchase_order_id bigint,
  order_number text,
  purchase_request_id bigint,
  supplier_id bigint,
  status text,
  subtotal numeric,
  discount_amount numeric,
  tax_amount numeric,
  total_amount numeric
)
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_request_number text;
  v_request_status text;
  v_supplier_id bigint;

  v_supplier_exists boolean;
  v_existing_order_id bigint;

  v_item_count integer := 0;
  v_invalid_item_count integer := 0;

  v_order_number text;
  v_purchase_order_id bigint;

  v_subtotal numeric(18, 2) := 0;
  v_discount_amount numeric(18, 2) := 0;
  v_tax_amount numeric(18, 2) := 0;
  v_total_amount numeric(18, 2) := 0;

  v_notes text;
begin
  -- ----------------------------------------------------------
  -- Validasi ID Purchase Request
  -- ----------------------------------------------------------
  if
    p_purchase_request_id is null
    or p_purchase_request_id < 1
  then
    raise exception
      using message =
        'ID permintaan pembelian tidak valid.';
  end if;

  -- ----------------------------------------------------------
  -- Validasi tanggal
  -- ----------------------------------------------------------
  if p_order_date is null then
    raise exception
      using message =
        'Tanggal Purchase Order wajib diisi.';
  end if;

  if
    p_expected_date is not null
    and p_expected_date < p_order_date
  then
    raise exception
      using message =
        'Tanggal kebutuhan tidak boleh lebih awal dari tanggal Purchase Order.';
  end if;

  -- ----------------------------------------------------------
  -- Validasi nilai potongan dan pajak
  -- ----------------------------------------------------------
  v_discount_amount :=
    coalesce(
      p_discount_amount,
      0
    );

  v_tax_amount :=
    coalesce(
      p_tax_amount,
      0
    );

  if v_discount_amount < 0 then
    raise exception
      using message =
        'Nilai potongan tidak boleh negatif.';
  end if;

  if v_tax_amount < 0 then
    raise exception
      using message =
        'Nilai pajak tidak boleh negatif.';
  end if;

  v_notes :=
    nullif(
      btrim(
        coalesce(
          p_notes,
          ''
        )
      ),
      ''
    );

  -- ----------------------------------------------------------
  -- Ambil dan kunci Purchase Request
  -- ----------------------------------------------------------
  select
    pr.request_number,
    pr.status,
    pr.supplier_id
  into
    v_request_number,
    v_request_status,
    v_supplier_id
  from public.purchase_requests as pr
  where pr.id = p_purchase_request_id
  for update;

  if not found then
    raise exception
      using message =
        'Permintaan pembelian tidak ditemukan.';
  end if;

  -- ----------------------------------------------------------
  -- Hanya PR approved yang dapat dikonversi
  -- ----------------------------------------------------------
  if v_request_status <> 'approved' then
    raise exception
      using message =
        format(
          'Permintaan pembelian %s tidak dapat dikonversi karena status saat ini adalah %s.',
          v_request_number,
          v_request_status
        );
  end if;

  -- ----------------------------------------------------------
  -- Supplier wajib tersedia
  -- ----------------------------------------------------------
  if v_supplier_id is null then
    raise exception
      using message =
        'Supplier pada permintaan pembelian wajib dipilih sebelum membuat Purchase Order.';
  end if;

  select exists (
    select 1
    from public.suppliers as s
    where
      s.id = v_supplier_id
      and s.is_active is true
  )
  into v_supplier_exists;

  if not v_supplier_exists then
    raise exception
      using message =
        'Supplier tidak ditemukan atau sudah tidak aktif.';
  end if;

  -- ----------------------------------------------------------
  -- Pastikan PR belum pernah dikonversi
  -- ----------------------------------------------------------
  select po.id
  into v_existing_order_id
  from public.purchase_orders as po
  where po.purchase_request_id = p_purchase_request_id
  limit 1;

  if v_existing_order_id is not null then
    raise exception
      using message =
        format(
          'Permintaan pembelian %s sudah pernah dikonversi menjadi Purchase Order.',
          v_request_number
        );
  end if;

  -- ----------------------------------------------------------
  -- Pastikan PR memiliki item
  -- ----------------------------------------------------------
  select count(*)
  into v_item_count
  from public.purchase_request_items as pri
  where pri.purchase_request_id = p_purchase_request_id;

  if v_item_count < 1 then
    raise exception
      using message =
        'Permintaan pembelian harus memiliki minimal satu item.';
  end if;

  -- ----------------------------------------------------------
  -- Validasi item dan produk
  -- ----------------------------------------------------------
  select count(*)
  into v_invalid_item_count
  from public.purchase_request_items as pri
  left join public.products as p
    on p.id = pri.product_id
  where
    pri.purchase_request_id = p_purchase_request_id
    and (
      p.id is null
      or p.is_active is not true
      or p.track_stock is not true
      or pri.quantity is null
      or pri.quantity <= 0
      or pri.unit_cost is null
      or pri.unit_cost < 0
    );

  if v_invalid_item_count > 0 then
    raise exception
      using message =
        'Terdapat produk atau item yang tidak valid pada permintaan pembelian.';
  end if;

  -- ----------------------------------------------------------
  -- Hitung subtotal berdasarkan sumber item
  -- ----------------------------------------------------------
  select
    coalesce(
      sum(
        pri.quantity
        * pri.unit_cost
      ),
      0
    )
  into v_subtotal
  from public.purchase_request_items as pri
  where pri.purchase_request_id = p_purchase_request_id;

  if v_discount_amount > v_subtotal then
    raise exception
      using message =
        'Nilai potongan tidak boleh lebih besar dari subtotal.';
  end if;

  v_total_amount :=
    v_subtotal
    - v_discount_amount
    + v_tax_amount;

  if v_total_amount < 0 then
    raise exception
      using message =
        'Total Purchase Order tidak boleh negatif.';
  end if;

  -- ----------------------------------------------------------
  -- Buat nomor Purchase Order
  -- ----------------------------------------------------------
  v_order_number :=
    public.generate_purchase_order_number();

  -- ----------------------------------------------------------
  -- Buat header Purchase Order
  -- ----------------------------------------------------------
  insert into public.purchase_orders (
    order_number,
    purchase_request_id,
    supplier_id,
    status,
    order_date,
    expected_date,
    notes,
    subtotal,
    discount_amount,
    tax_amount,
    total_amount
  )
  values (
    v_order_number,
    p_purchase_request_id,
    v_supplier_id,
    'draft',
    p_order_date,
    p_expected_date,
    v_notes,
    v_subtotal,
    v_discount_amount,
    v_tax_amount,
    v_total_amount
  )
  returning id
  into v_purchase_order_id;

  -- ----------------------------------------------------------
  -- Salin item Purchase Request ke Purchase Order
  -- ----------------------------------------------------------
  insert into public.purchase_order_items (
    purchase_order_id,
    product_id,
    quantity,
    received_quantity,
    unit_cost,
    subtotal,
    notes
  )
  select
    v_purchase_order_id,
    pri.product_id,
    pri.quantity,
    0,
    pri.unit_cost,
    pri.quantity * pri.unit_cost,
    pri.notes
  from public.purchase_request_items as pri
  where pri.purchase_request_id = p_purchase_request_id
  order by pri.id;

  -- ----------------------------------------------------------
  -- Ubah status Purchase Request menjadi converted
  -- ----------------------------------------------------------
  update public.purchase_requests
  set
    status = 'converted',
    updated_at = now()
  where id = p_purchase_request_id;

  -- ----------------------------------------------------------
  -- Return hasil
  -- ----------------------------------------------------------
  return query
  select
    v_purchase_order_id,
    v_order_number,
    p_purchase_request_id,
    v_supplier_id,
    'draft'::text,
    v_subtotal,
    v_discount_amount,
    v_tax_amount,
    v_total_amount;
end;
$$;


-- ============================================================
-- 8. HAK AKSES FUNCTION
-- ============================================================

revoke all
on function public.generate_purchase_order_number()
from public;

grant execute
on function public.generate_purchase_order_number()
to authenticated;


revoke all
on function public.create_purchase_order_from_request(
  bigint,
  date,
  date,
  text,
  numeric,
  numeric
)
from public;

grant execute
on function public.create_purchase_order_from_request(
  bigint,
  date,
  date,
  text,
  numeric,
  numeric
)
to authenticated;


-- ============================================================
-- 9. HAK AKSES TABEL
-- ============================================================

grant select, insert, update, delete
on table public.purchase_orders
to authenticated;

grant select, insert, update, delete
on table public.purchase_order_items
to authenticated;

grant usage, select
on sequence public.purchase_order_number_seq
to authenticated;