begin;

-- =========================================================
-- 1. Sequence nomor Goods Receipt
-- =========================================================

create sequence if not exists public.goods_receipt_number_seq
    start with 1
    increment by 1
    minvalue 1;


-- =========================================================
-- 2. Tabel Goods Receipt
-- =========================================================

create table if not exists public.goods_receipts (
    id bigint generated by default as identity primary key,

    receipt_number text not null,
    purchase_order_id bigint not null,
    supplier_id bigint not null,

    status text not null default 'posted',

    receipt_date date not null default current_date,
    reference_number text,
    notes text,

    total_items integer not null default 0,
    total_quantity numeric not null default 0,
    total_amount numeric not null default 0,

    posted_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    cancellation_reason text,

    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    constraint goods_receipts_receipt_number_unique
        unique (receipt_number),

    constraint goods_receipts_purchase_order_id_fkey
        foreign key (purchase_order_id)
        references public.purchase_orders(id)
        on update cascade
        on delete restrict,

    constraint goods_receipts_supplier_id_fkey
        foreign key (supplier_id)
        references public.suppliers(id)
        on update cascade
        on delete restrict,

    constraint goods_receipts_status_valid
        check (
            status = any (
                array[
                    'draft'::text,
                    'posted'::text,
                    'cancelled'::text
                ]
            )
        ),

    constraint goods_receipts_total_items_non_negative
        check (total_items >= 0),

    constraint goods_receipts_total_quantity_non_negative
        check (total_quantity >= 0),

    constraint goods_receipts_total_amount_non_negative
        check (total_amount >= 0),

    constraint goods_receipts_cancellation_reason_valid
        check (
            cancellation_reason is null
            or char_length(trim(cancellation_reason)) > 0
        )
);


-- =========================================================
-- 3. Tabel Goods Receipt Items
-- =========================================================

create table if not exists public.goods_receipt_items (
    id bigint generated by default as identity primary key,

    goods_receipt_id bigint not null,
    purchase_order_item_id bigint not null,
    product_id bigint not null,

    quantity_received numeric not null,
    unit_cost numeric not null,

    subtotal numeric generated always as (
        quantity_received * unit_cost
    ) stored,

    notes text,

    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    constraint goods_receipt_items_goods_receipt_id_fkey
        foreign key (goods_receipt_id)
        references public.goods_receipts(id)
        on update cascade
        on delete cascade,

    constraint goods_receipt_items_purchase_order_item_id_fkey
        foreign key (purchase_order_item_id)
        references public.purchase_order_items(id)
        on update cascade
        on delete restrict,

    constraint goods_receipt_items_product_id_fkey
        foreign key (product_id)
        references public.products(id)
        on update cascade
        on delete restrict,

    constraint goods_receipt_items_receipt_po_item_unique
        unique (
            goods_receipt_id,
            purchase_order_item_id
        ),

    constraint goods_receipt_items_quantity_positive
        check (quantity_received > 0),

    constraint goods_receipt_items_unit_cost_non_negative
        check (unit_cost >= 0)
);


-- =========================================================
-- 4. Index
-- =========================================================

create index if not exists goods_receipts_purchase_order_id_idx
    on public.goods_receipts(purchase_order_id);

create index if not exists goods_receipts_supplier_id_idx
    on public.goods_receipts(supplier_id);

create index if not exists goods_receipts_receipt_date_idx
    on public.goods_receipts(receipt_date desc);

create index if not exists goods_receipts_status_idx
    on public.goods_receipts(status);

create index if not exists goods_receipt_items_goods_receipt_id_idx
    on public.goods_receipt_items(goods_receipt_id);

create index if not exists goods_receipt_items_purchase_order_item_id_idx
    on public.goods_receipt_items(purchase_order_item_id);

create index if not exists goods_receipt_items_product_id_idx
    on public.goods_receipt_items(product_id);


-- =========================================================
-- 5. Trigger updated_at
-- =========================================================

drop trigger if exists set_goods_receipts_updated_at
    on public.goods_receipts;

create trigger set_goods_receipts_updated_at
before update on public.goods_receipts
for each row
execute function public.set_updated_at();


drop trigger if exists set_goods_receipt_items_updated_at
    on public.goods_receipt_items;

create trigger set_goods_receipt_items_updated_at
before update on public.goods_receipt_items
for each row
execute function public.set_updated_at();


-- =========================================================
-- 6. Generator nomor Goods Receipt
-- Format: GR-YYYYMM-000001
-- =========================================================

create or replace function public.generate_goods_receipt_number()
returns text
language plpgsql
set search_path = public
as $$
declare
    v_sequence_number bigint;
begin
    v_sequence_number :=
        nextval(
            'public.goods_receipt_number_seq'
        );

    return
        'GR-' ||
        to_char(current_date, 'YYYYMM') ||
        '-' ||
        lpad(
            v_sequence_number::text,
            6,
            '0'
        );
end;
$$;


-- =========================================================
-- 7. RPC Create Goods Receipt
--
-- Format p_items:
-- [
--   {
--     "purchaseOrderItemId": 1,
--     "quantityReceived": 10,
--     "unitCost": 25000,
--     "notes": "Kondisi baik"
--   }
-- ]
-- =========================================================

create or replace function public.create_goods_receipt(
    p_purchase_order_id bigint,
    p_receipt_date date,
    p_reference_number text default null,
    p_notes text default null,
    p_items jsonb default '[]'::jsonb
)
returns table (
    goods_receipt_id bigint,
    receipt_number text,
    purchase_order_id bigint,
    purchase_order_status text,
    total_items integer,
    total_quantity_received numeric,
    total_amount numeric
)
language plpgsql
security invoker
set search_path = public
as $$
declare
    v_purchase_order public.purchase_orders%rowtype;
    v_purchase_order_item public.purchase_order_items%rowtype;
    v_product public.products%rowtype;

    v_goods_receipt_id bigint;
    v_receipt_number text;

    v_item jsonb;
    v_purchase_order_item_id bigint;
    v_quantity_received numeric;
    v_unit_cost numeric;
    v_item_notes text;

    v_remaining_quantity numeric;

    v_total_items integer := 0;
    v_total_quantity numeric := 0;
    v_total_amount numeric := 0;

    v_total_ordered_quantity numeric := 0;
    v_total_received_quantity numeric := 0;

    v_purchase_order_status text;
begin
    if p_purchase_order_id is null
       or p_purchase_order_id < 1 then
        raise exception
            'Purchase Order tidak valid.';
    end if;

    if p_receipt_date is null then
        raise exception
            'Tanggal penerimaan wajib diisi.';
    end if;

    if p_items is null
       or jsonb_typeof(p_items) <> 'array'
       or jsonb_array_length(p_items) = 0 then
        raise exception
            'Minimal satu barang harus diterima.';
    end if;

    select *
    into v_purchase_order
    from public.purchase_orders
    where id = p_purchase_order_id
    for update;

    if not found then
        raise exception
            'Purchase Order tidak ditemukan.';
    end if;

    if v_purchase_order.status not in (
        'sent',
        'confirmed',
        'partial_received'
    ) then
        raise exception
            'Purchase Order dengan status % tidak dapat menerima barang.',
            v_purchase_order.status;
    end if;

    v_receipt_number :=
        public.generate_goods_receipt_number();

    insert into public.goods_receipts (
        receipt_number,
        purchase_order_id,
        supplier_id,
        status,
        receipt_date,
        reference_number,
        notes,
        posted_at
    )
    values (
        v_receipt_number,
        v_purchase_order.id,
        v_purchase_order.supplier_id,
        'posted',
        p_receipt_date,
        nullif(
            trim(p_reference_number),
            ''
        ),
        nullif(
            trim(p_notes),
            ''
        ),
        now()
    )
    returning id
    into v_goods_receipt_id;

    for v_item in
        select value
        from jsonb_array_elements(p_items)
    loop
        begin
            v_purchase_order_item_id :=
                nullif(
                    v_item ->> 'purchaseOrderItemId',
                    ''
                )::bigint;

            v_quantity_received :=
                nullif(
                    v_item ->> 'quantityReceived',
                    ''
                )::numeric;

            v_unit_cost :=
                nullif(
                    v_item ->> 'unitCost',
                    ''
                )::numeric;

            v_item_notes :=
                nullif(
                    trim(
                        v_item ->> 'notes'
                    ),
                    ''
                );
        exception
            when others then
                raise exception
                    'Format item penerimaan tidak valid.';
        end;

        if v_purchase_order_item_id is null
           or v_purchase_order_item_id < 1 then
            raise exception
                'Item Purchase Order tidak valid.';
        end if;

        if v_quantity_received is null
           or v_quantity_received <= 0 then
            raise exception
                'Jumlah penerimaan harus lebih besar dari nol.';
        end if;

        select *
        into v_purchase_order_item
        from public.purchase_order_items
        where id = v_purchase_order_item_id
          and purchase_order_id = p_purchase_order_id
        for update;

        if not found then
            raise exception
                'Item Purchase Order % tidak ditemukan.',
                v_purchase_order_item_id;
        end if;

        v_remaining_quantity :=
            v_purchase_order_item.quantity -
            v_purchase_order_item.received_quantity;

        if v_quantity_received >
           v_remaining_quantity then
            raise exception
                'Jumlah penerimaan produk % melebihi sisa pesanan. Sisa yang dapat diterima: %.',
                v_purchase_order_item.product_id,
                v_remaining_quantity;
        end if;

        if v_unit_cost is null then
            v_unit_cost :=
                v_purchase_order_item.unit_cost;
        end if;

        if v_unit_cost < 0 then
            raise exception
                'Harga satuan tidak boleh negatif.';
        end if;

        if exists (
            select 1
            from public.goods_receipt_items gri
            where gri.goods_receipt_id =
                    v_goods_receipt_id
              and gri.purchase_order_item_id =
                    v_purchase_order_item_id
        ) then
            raise exception
                'Item Purchase Order % dikirim lebih dari satu kali dalam penerimaan yang sama.',
                v_purchase_order_item_id;
        end if;

        insert into public.goods_receipt_items (
            goods_receipt_id,
            purchase_order_item_id,
            product_id,
            quantity_received,
            unit_cost,
            notes
        )
        values (
            v_goods_receipt_id,
            v_purchase_order_item.id,
            v_purchase_order_item.product_id,
            v_quantity_received,
            v_unit_cost,
            v_item_notes
        );

        update public.purchase_order_items
        set
            received_quantity =
                received_quantity +
                v_quantity_received,
            updated_at = now()
        where id =
            v_purchase_order_item.id;

        select *
        into v_product
        from public.products
        where id =
            v_purchase_order_item.product_id
        for update;

        if not found then
            raise exception
                'Produk % tidak ditemukan.',
                v_purchase_order_item.product_id;
        end if;

        if v_product.track_stock then
            update public.products
            set
                stock =
                    stock +
                    v_quantity_received,
                updated_at = now()
            where id =
                v_product.id;

            insert into public.inventory_movements (
                product_id,
                supplier_id,
                sale_id,
                movement_type,
                quantity,
                unit_cost,
                reference_number,
                notes,
                movement_date
            )
            values (
                v_product.id,
                v_purchase_order.supplier_id,
                null,
                'purchase',
                v_quantity_received,
                v_unit_cost,
                v_receipt_number,
                concat(
                    'Penerimaan barang ',
                    v_receipt_number,
                    ' dari PO ',
                    v_purchase_order.order_number,
                    case
                        when v_item_notes is not null
                        then ' - ' || v_item_notes
                        else ''
                    end
                ),
                now()
            );
        end if;

        v_total_items :=
            v_total_items + 1;

        v_total_quantity :=
            v_total_quantity +
            v_quantity_received;

        v_total_amount :=
            v_total_amount +
            (
                v_quantity_received *
                v_unit_cost
            );
    end loop;

    update public.goods_receipts
    set
        total_items =
            v_total_items,
        total_quantity =
            v_total_quantity,
        total_amount =
            v_total_amount,
        updated_at = now()
    where id =
        v_goods_receipt_id;

    select
        coalesce(
            sum(quantity),
            0
        ),
        coalesce(
            sum(received_quantity),
            0
        )
    into
        v_total_ordered_quantity,
        v_total_received_quantity
    from public.purchase_order_items
    where purchase_order_id =
        p_purchase_order_id;

    if v_total_received_quantity >=
       v_total_ordered_quantity then
        v_purchase_order_status :=
            'completed';

        update public.purchase_orders
        set
            status = 'completed',
            completed_at =
                coalesce(
                    completed_at,
                    now()
                ),
            updated_at = now()
        where id =
            p_purchase_order_id;
    else
        v_purchase_order_status :=
            'partial_received';

        update public.purchase_orders
        set
            status =
                'partial_received',
            completed_at = null,
            updated_at = now()
        where id =
            p_purchase_order_id;
    end if;

    return query
    select
        v_goods_receipt_id,
        v_receipt_number,
        p_purchase_order_id,
        v_purchase_order_status,
        v_total_items,
        v_total_quantity,
        v_total_amount;
end;
$$;


-- =========================================================
-- 8. Hak akses RPC
-- =========================================================

grant execute
on function public.generate_goods_receipt_number()
to authenticated;

grant execute
on function public.create_goods_receipt(
    bigint,
    date,
    text,
    text,
    jsonb
)
to authenticated;


commit;